plugins {
    id 'idea'
    id 'java'
    id 'com.azuredoom.hytale-tools' version '1.+'
    id 'com.azuredoom.hytalepublisher' version '1.1.7'
    id 'com.gradleup.shadow' version '9.4.2'
}


configurations {
    shaded
    implementation.extendsFrom(shaded)
}

dependencies {
    vineImplementation 'curse.maven:hexcode-1448311:8758841'
    shaded('com.riprod:patchly:3.+')
}

shadowJar {
    archiveClassifier.set('')
    mergeServiceFiles()
    configurations = [project.configurations.shaded]
}

tasks.build {
    dependsOn("shadowJar")
}

javadoc {
    options.addStringOption('Xdoclint:-missing', '-quiet')
}

group = project.group

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
}

hytaleTools {
    javaVersion = project.java_version as Integer
    hytaleVersion = project.hytale_version.toString()
    manifestGroup = project.manifest_group.toString()
    modId = project.mod_id.toString()
    modDescription = project.mod_description.toString()
    modUrl = project.mod_url.toString()
    mainClass = project.main_class.toString()
    modCredits = project.mod_author.toString()
    manifestDependencies = project.manifest_dependencies.toString()
    manifestOptionalDependencies = project.manifest_opt_dependencies.toString()
    curseforgeId = project.curseforgeID.toString()
    disabledByDefault = project.disabled_by_default.toString().toBoolean()
    includesPack = project.includes_pack.toString().toBoolean()
    patchline = project.patchline.toString()
}

repositories {
    mavenCentral()
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

hytalePublisher {
    modtale {
        enabled = true
        projectId = project.modtale_project_id.toString()
    }

    curseforge {
        enabled = true
        projectId = project.curseforge_project_id.toString()
    }

    modifold {
        enabled = true
        projectId = project.modifold_project_slug.toString()
    }
}
